theluupe/marketplace

- package.json
- server/api/auth/auth0.js
- src/components/Marquee/Marquee.js
- src/components/Marquee/Marquee.module.css
- src/components/Marquee/icons/IconArrow.js
- src/components/Marquee/icons/IconCircle.js
- src/components/index.js
- src/containers/AuthenticationPage/AuthenticationForms/AuthenticationForms.js
- src/containers/AuthenticationPage/AuthenticationForms/AuthenticationForms.module.css
- src/containers/AuthenticationPage/AuthenticationPage.js
- src/containers/AuthenticationPage/AuthenticationPage.module.css
- src/containers/AuthenticationPage/ConfirmSignupForm/ConfirmSignupForm.js
- src/styles/marketplaceDefaults.css
- src/util/userHelpers.js
- yarn.lock
Added Marquee and custom ConfirmationPage UI
> Added Marquee and custom ConfirmationPage UI

- .gitignore
- craco.config.js
- public/index.html
- server/csp.js
- src/app.js
- src/containers/BatchEditListingPage/BatchEditListingPage.duck.js
- src/containers/BatchEditListingPage/BatchEditListingPage.js
- src/containers/BatchEditListingPage/BatchEditListingWizard/BatchEditListingProductDetails/EditableListingsTable.js
- src/containers/BatchEditListingPage/BatchEditListingWizard/BatchEditListingUploaderPanel/EditListingUploaderPanel.js
- src/containers/BatchEditListingPage/BatchEditListingWizard/BatchEditListingWizard.js
- src/index.js
- src/reducers.js
- src/store.js
- src/util/uppy.js
- Ensure Uppy is only referenced by client-side code, as its ES Modules are incompatible with server-side CommonJS code.
- Load Uppy libraries asynchronously to avoid runtime issues.
- Move Uppy CSS references to the HTML page, as loading them from JavaScript was causing runtime issues in the production bundle.
- Add Content Security Policy (CSP) rules for Uppy’s styles and the JavaScript worker file used by the Golden Retriever plugin.
- Add or correct several properties used during listing creation:
- Ensure file type is assigned correctly.
- Set the category by inferring it from the file type rather than path parameters.
- `imageSize` now receives accurate values.
- Add `transactionProcessAlias` and `unitType`, which are pulled from the "product-listing" category configuration. These …
> Enhance Uppy Integration and Fix Listing Property Assignments for Stability in Production

- src/containers/BatchEditListingPage/BatchEditListingPage.duck.js
- src/containers/BatchEditListingPage/BatchEditListingWizard/BatchEditListingProductDetails/EditableListingsTable.js
Fix product listing issues related to React downgrade
> Fix product listing issues related to React downgrade

- server/api-util/scriptManager.js
- server/api-util/slackHelper/index.js
- server/api-util/slackHelper/productListingsCreatedBlocks.js
- server/scripts/events/notifyProductListingCreated.js
Send SLACK notification when a new batch of Product Listings is generated
> Listings | notify product listing created

- package.json
- server/scripts/events/notifyProductListingCreated.js
- src/components/ScrollableLinks/ScrollableLinks.js
- src/components/ScrollableLinks/ScrollableLinks.module.css
- src/containers/BatchEditListingPage/BatchEditListingPage.duck.js
- src/containers/BatchEditListingPage/BatchEditListingPage.js
- src/containers/BatchEditListingPage/BatchEditListingPage.module.css
- src/containers/BatchEditListingPage/BatchEditListingWizard/BatchEditListingProductDetails/EditListingBatchProductDetails.js
- src/containers/BatchEditListingPage/BatchEditListingWizard/BatchEditListingProductDetails/EditListingBatchProductDetails.module.css
- src/containers/BatchEditListingPage/BatchEditListingWizard/BatchEditListingProductDetails/EditableCellComponents.js
- src/containers/BatchEditListingPage/BatchEditListingWizard/BatchEditListingProductDetails/EditableListingsTable.js
- src/containers/BatchEditListingPage/BatchEditListingWizard/BatchEditListingResult/BatchEditListingResult.js
- src/containers/BatchEditListingPage/BatchEditListingWizard/BatchEditListingUploaderPanel/EditListingUploaderPanel.js
- src/containers/BatchEditListingPage/BatchEditListingWizard/BatchEditListingWizard.js
- src/containers/BatchEditListingPage/ProductListingsEditMode/ProductsListingEditMode.js
- src/containers/BatchEditListingPage/constants.js
- src/containers/BatchEditListingPage/imageHelpers.js
- src/containers/ManageListingsPage/ManageListingsPage.js
- src/containers/ManageListingsPage/ManageListingsPage.module.css
- src/routing/routeConfiguration.js
- src/styles/marketplaceDefaults.css
- src/translations/en.json
- src/util/file-metadata.js
- src/util/file-metadata.test.js
- yarn.lock
This PR introduces several updates to improve the product listing feature and enhance the user interface for managing product listings. Key changes include:
1. **Implement Product Listing Edition**  
- Added functionality to enable users to edit existing product listings.
2. **Update Product Listing URL Structure**  
- Changed the URL for product listings to follow the format:  
`/l/products/{mode:new|edit}`  
This enables better clarity and flexibility for distinguishing between creating and editing listings.
3. **Refactor Constants**  
- Moved constants to a separate file to declutter the duck file, improving maintainability and readability of the codebase.
4. **Add "Manage <PRODUCT TYPE>" Button**  
- Included a button on the listings page for users to easily access the edit …
> Implement Product Listing Edition and Enhance Listings Page

- src/containers/BatchEditListingPage/BatchEditListingPage.duck.js
- src/containers/BatchEditListingPage/imageHelpers.js
- src/util/string.js
Avoid page loading errors by handling the following gracefully:
Empty or invalid keywords and categories
Missing or null prices
Incorrect image dimensions
> Enhance error tolerance for invalid inputs and missing data on product page load for editing mode

- src/containers/BatchEditListingPage/BatchEditListingPage.duck.js
- src/containers/BatchEditListingPage/BatchEditListingWizard/BatchEditListingProductDetails/EditableCellComponents.js
- src/containers/BatchEditListingPage/BatchEditListingWizard/BatchEditListingProductDetails/EditableListingsTable.js
- src/containers/BatchEditListingPage/BatchEditListingWizard/CsvUpload/CsvUpload.js
- src/containers/BatchEditListingPage/constants.js
- "Releases" column value now is set to false by default
- Category filter in product edition mode was not working
- Fix limiting categories to 5
> Several fixes

- server/api-util/scriptManager.js
- server/api-util/slackHelper/index.js
- server/api-util/slackHelper/productListingsErrorBlocks.js
- server/api-util/slackHelper/profileListingUpdateErrorBlocks.js
- server/api-util/slackHelper/userCreatedErrorBlocks.js
- server/api-util/slackHelper/userUpdatedErrorBlocks.js
- server/api-util/storageManagerHelper.js
- server/scripts/events/notifyProductListingCreated.js
- server/scripts/events/notifyProfileListingUpdated.js
- server/scripts/events/notifyUserCreated.js
- server/scripts/events/notifyUserUpdated.js
- src/util/api.js
- src/util/uppy.js
Async improvements
Storage-manager batch endpoints
> Storage-manager improvements

- server/api-util/scriptManager.js
- src/components/ListingCard/ListingCard.js
- src/components/ListingTabs/ListingTabs.js
- src/containers/BatchEditListingPage/BatchEditListingPage.duck.js
- src/containers/BatchEditListingPage/constants.js
- src/containers/FavoriteListingsPage/FavoriteListingsPage.duck.js
- src/containers/ManageListingsPage/ManageListingsPage.duck.js
- src/containers/ManageListingsPage/ManageListingsPage.js
- src/containers/ManageListingsPage/utils.js
- src/containers/ProfilePage/ProfilePage.duck.js
- src/containers/ProfilePage/SellerProfilePage/SellerProfilePage.js
- src/util/uppy.js
- src/util/urlHelpers.js
Fixed Listing pagination
Minor UX fixes
Set production ready delays
Disable Product videos
> Release fixes

- src/components/ListingTabs/ListingTabs.js
- src/containers/ManageListingsPage/utils.js
Fixes:
- Portfolio editing navigation.
- Display of portfolios without videos.
> Portfolio listing fixes

- package.json
- src/components/ListingTabs/GridHelpers.js
- yarn.lock
Restrict the times when new listings can be published
> Scheduled uploads

- server/api-util/scriptManager.js
- server/scripts/events/notifyProductListingCreated.js
Don't execute handlers on empty events
Improved the way we stored the assets and changed the metadata
> Storage manager improvements

- server/api-util/retryAsync.js
- server/api-util/scriptManager.js
- server/scripts/events/notifyProductListingCreated.js
- src/containers/BatchEditListingPage/BatchEditListingPage.duck.js
Store the tempFileURLs and don't delete them in case we gotta recover from an error
Add a pollLoop timeout in case the app hangs
Improve debugging logs
> PollLoop improvements

- server/api-util/scriptManager.js
- server/api-util/slackHelper/index.js
- server/api-util/slackHelper/productListingsFieldsErrorBlocks.js
- server/scripts/events/index.js
- server/scripts/events/notifyProductListingCreated.js
- src/containers/BatchEditListingPage/BatchEditListingPage.duck.js
- src/containers/BatchEditListingPage/BatchEditListingWizard/BatchEditListingProductDetails/EditListingBatchProductDetails.module.css
- src/containers/BatchEditListingPage/BatchEditListingWizard/BatchEditListingProductDetails/EditableListingsTable.js
- src/containers/BatchEditListingPage/BatchEditListingWizard/BatchEditListingProductDetails/TableHeaderTitle.js
Multiple UX warning fixes
Disabled "notifyProductListingCreated" on PROD until we fix the storage-manager
Added slack alert when we get Products without ALL the needed information
> Multiple UX warning fixes

- server/api-util/scriptManager.js
- src/containers/BatchEditListingPage/BatchEditListingPage.duck.js
Improved the "delay" and "lastSequenceId" values update
Improved the poolWait times
Removed the default "title" for the assets
Autoselect all products while editing them
> Storage-manager performance improvements v1

- server/api-util/httpHelpers.js
- server/api-util/retryAsync.js
- server/api-util/scriptManager.js
- server/api-util/storageManagerHelper.js
- server/scripts/events/index.js
- server/scripts/events/notifyProductListingCreated.js
Improved logging
Improved different delays and timouts
Removed marketplace batch upload feature
> Removed marketplace batch upload feature

- src/components/ListingTabs/GridHelpers.js
- src/components/ListingTabs/ListingTabs.js
- src/containers/FavoriteListingsPage/FavoriteListingsPage.duck.js
- src/containers/ListingPage/ListingPage.shared.js
- src/containers/ListingPage/ListingPageCarousel.js
- src/containers/ListingPage/ListingPageCoverPhoto.js
- src/containers/ListingPage/SectionAuthorMaybe.js
- src/containers/ProfilePage/ProfilePage.js
- src/containers/ProfilePage/ProfilePage.module.css
- src/containers/ProfilePage/SellerProfilePage/ProfileInfo.js
- src/containers/ProfilePage/SellerProfilePage/SellerProfilePage.js
- src/translations/en.json
Fixed Shop pagination
Fixed favorite "show-all" bug
Request to book form
> Request to book and Pagination fixes

- src/transactions/transactionProcessPurchase.js
Added the INQUIRE transitions to the Purchase process just as a fallback value to validate the code
> INQUIRE fixes on the Purchase process

- src/containers/BatchEditListingPage/BatchEditListingPage.duck.js
- src/containers/BatchEditListingPage/BatchEditListingWizard/BatchEditListingProductDetails/EditListingBatchProductDetails.js
- src/containers/BatchEditListingPage/BatchEditListingWizard/BatchEditListingProductDetails/EditableListingsTable.js
- src/containers/ProfilePage/ProfilePage.module.css
- src/containers/ProfilePage/SellerProfilePage/ProfileInfo.js
- src/util/types.js
- src/util/urlHelpers.js
- src/util/userHelpers.js
* Toggle issue for the release information (edit and new). This was a…lso happening on the illustration toggle but we didn’t notice
* Remove What Describes You + Pronouns from About Section
* Prefer Not To Say Pronoun -- Remove (if)
* Seller Profile | Portfolio URL - Added ellipsis “…” when the URL was too long - Removed the protocol (“http” or “https”) - Removed the “www”
> Open Beta | UX improvements V1

- server/api-util/slackHelper/index.js
- server/api-util/slackHelper/sellerValidationBlocks.js
- server/api/scripts-retry/index.js
- server/api/scripts-retry/retryProductListingCreated.js
- server/api/scripts-retry/retryUserCreated.js
- server/apiRouter.js
- server/scripts/events/notifyUserCreated.js
- server/scripts/events/notifyUserUpdated.js
Retry the Seller approval slack flow in case we want to accept into the community a previously waitlisted Creator
> Retry Seller approval

- src/containers/TopbarContainer/TopbarContainer.js
- src/ducks/auth.duck.js
> Auth0 session logout

- server/scripts/events/index.js
- server/scripts/events/notifyProductListingRejected.js
- src/containers/FavoriteListingsPage/FavoriteListingsPage.duck.js
- src/ducks/auth.duck.js
Manage Product Listing rejection
Fixed Favorites bug
> Manage Product Listing rejection

- server/scripts/events/notifyUserCreated.js
Catch referral factory errors so they don't stop a new user creation
> Referral-factory fixes

- server/resources/robotsTxt.js
- server/resources/sitemap.js
> Analytics | SEO qa improvements
